# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCaso1():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_caso1(self):
    # Test name: caso1
    # Step # | name | target | value
    # 1 | open | /testing2024/tareamiercoles/formtarea.html | 
    self.driver.get("http://127.0.0.1/testing2024/tareamiercoles/formtarea.html")
    # 2 | setWindowSize | 940x728 | 
    self.driver.set_window_size(940, 728)
    # 3 | click | id=nombre | 
    self.driver.find_element(By.ID, "nombre").click()
    # 4 | type | id=nombre | fabian
    self.driver.find_element(By.ID, "nombre").send_keys("fabian")
    # 5 | click | id=apellido | 
    self.driver.find_element(By.ID, "apellido").click()
    # 6 | type | id=apellido | dragonetti
    self.driver.find_element(By.ID, "apellido").send_keys("dragonetti")
    # 7 | click | id=dni | 
    self.driver.find_element(By.ID, "dni").click()
    # 8 | type | id=dni | 30895510
    self.driver.find_element(By.ID, "dni").send_keys("30895510")
    # 9 | click | id=fecha | 
    self.driver.find_element(By.ID, "fecha").click()
    # 10 | type | id=fecha | 1984-03-28
    self.driver.find_element(By.ID, "fecha").send_keys("1984-03-28")
    # 11 | click | css=#grupogenero > .grupoforminput | 
    self.driver.find_element(By.CSS_SELECTOR, "#grupogenero > .grupoforminput").click()
    # 12 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 13 | type | id=email | fabiandragonetti@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("fabiandragonetti@gmail.com")
    # 14 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 15 | type | id=password | 111111111111111
    self.driver.find_element(By.ID, "password").send_keys("111111111111111")
    # 16 | click | id=password2 | 
    self.driver.find_element(By.ID, "password2").click()
    # 17 | type | id=password2 | 111111111111111
    self.driver.find_element(By.ID, "password2").send_keys("111111111111111")
    # 18 | click | id=terminos | 
    self.driver.find_element(By.ID, "terminos").click()
    # 19 | click | id=btn_register | 
    self.driver.find_element(By.ID, "btn_register").click()
    # 20 | click | id=btn_register | 
    self.driver.find_element(By.ID, "btn_register").click()
  
